// ==============================================================================
// GHITA CODING AGENT - Built-in Skill: Presentation Deck Generator
// ==============================================================================
// Absorbed from Presenton reference project (AI Presentation Generator & API).
// Converts raw text/markdown outlines into structured slide deck ASTs, HTML, and Marp slides.
// ==============================================================================

import type { SkillDefinition } from '../types.js';
import { SKILLS_VERSION } from '../types.js';
import { ok, fail, readString } from '../helpers.js';

export interface SlideComponent {
  type: 'heading' | 'text' | 'code' | 'list' | 'image' | 'quote';
  content: string;
  language?: string;
  items?: string[];
}

export interface Slide {
  id: string;
  title: string;
  subtitle?: string;
  layout: 'title' | 'content' | 'split' | 'code-focus' | 'quote';
  components: SlideComponent[];
  notes?: string;
}

export interface SlideDeck {
  title: string;
  author?: string;
  theme: 'dark' | 'light' | 'ghita-neon' | 'cyberpunk';
  slides: Slide[];
}

/** Converts a Markdown/Text outline into a structured SlideDeck AST. */
export function generateSlideDeck(
  title: string,
  rawOutline: string,
  theme: SlideDeck['theme'] = 'ghita-neon',
): SlideDeck {
  const sections = rawOutline.split(/\n(?=#{1,3}\s)/).filter((s) => s.trim().length > 0);

  const slides: Slide[] = [
    {
      id: 'slide-0',
      title,
      subtitle: 'Generated by GHITA CODING AGENT',
      layout: 'title',
      components: [
        {
          type: 'text',
          content: 'Architecture & Technical Overview Presentation',
        },
      ],
    },
  ];

  sections.forEach((sec, idx) => {
    const lines = sec.trim().split('\n');
    const firstLine = lines[0] ?? `Section ${idx + 1}`;
    const slideTitle = firstLine.replace(/^#{1,3}\s*/, '').trim();
    const contentBody = lines.slice(1).join('\n').trim();

    const isCode = contentBody.includes('```');
    const isList = contentBody
      .split('\n')
      .some((l) => l.trim().startsWith('- ') || l.trim().startsWith('* '));

    const components: SlideComponent[] = [];

    if (isCode) {
      const codeMatch = contentBody.match(/```(\w+)?\n([\s\S]*?)```/);
      if (codeMatch) {
        components.push({
          type: 'code',
          language: codeMatch[1] ?? 'ts',
          content: codeMatch[2]?.trim() ?? '',
        });
      }
    } else if (isList) {
      const listItems = contentBody
        .split('\n')
        .filter((l) => l.trim().startsWith('- ') || l.trim().startsWith('* '))
        .map((l) => l.trim().replace(/^[-*]\s*/, ''));
      components.push({
        type: 'list',
        content: 'Key Points:',
        items: listItems,
      });
    } else {
      components.push({
        type: 'text',
        content: contentBody || 'No additional content provided.',
      });
    }

    slides.push({
      id: `slide-${idx + 1}`,
      title: slideTitle,
      layout: isCode ? 'code-focus' : isList ? 'split' : 'content',
      components,
    });
  });

  return {
    title,
    author: 'GHITA CODING AGENT Engine',
    theme,
    slides,
  };
}

/** Renders a SlideDeck AST to a self-contained Marp / HTML Presentation string. */
export function renderSlideDeckToHTML(deck: SlideDeck): string {
  const slideElements = deck.slides
    .map((slide, idx) => {
      const componentsHTML = slide.components
        .map((comp) => {
          if (comp.type === 'code') {
            return `<pre><code class="language-${comp.language ?? 'text'}">${escapeHTML(comp.content)}</code></pre>`;
          }
          if (comp.type === 'list' && comp.items) {
            return `<ul>${comp.items.map((it) => `<li>${escapeHTML(it)}</li>`).join('')}</ul>`;
          }
          return `<p>${escapeHTML(comp.content)}</p>`;
        })
        .join('');

      return `
      <section class="slide slide-layout-${slide.layout}" id="${slide.id}">
        <div class="slide-header">
          <span class="slide-number">Slide ${idx + 1}/${deck.slides.length}</span>
          <h2>${escapeHTML(slide.title)}</h2>
          ${slide.subtitle ? `<h3>${escapeHTML(slide.subtitle)}</h3>` : ''}
        </div>
        <div class="slide-body">
          ${componentsHTML}
        </div>
      </section>`;
    })
    .join('\n<hr/>\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${escapeHTML(deck.title)} - GHITA Presentation</title>
  <style>
    body { font-family: system-ui, -apple-system, sans-serif; background: #0b0f19; color: #f3f4f6; margin: 0; padding: 40px; }
    .slide { background: #111827; border: 1px solid #1f2937; border-radius: 12px; padding: 32px; margin-bottom: 24px; box-shadow: 0 10px 25px rgba(0,0,0,0.5); }
    .slide-number { font-size: 0.75rem; color: #6b7280; text-transform: uppercase; letter-spacing: 0.05em; }
    h2 { color: #38bdf8; margin-top: 8px; font-size: 1.75rem; }
    h3 { color: #9ca3af; font-weight: 400; }
    pre { background: #030712; padding: 16px; border-radius: 8px; overflow-x: auto; color: #a7f3d0; }
    ul { line-height: 1.7; color: #e5e7eb; }
    li { margin-bottom: 8px; }
    hr { border: 0; height: 1px; background: #1f2937; margin: 40px 0; }
  </style>
</head>
<body>
  <h1>${escapeHTML(deck.title)}</h1>
  <p><strong>Theme:</strong> ${deck.theme} | <strong>Slides:</strong> ${deck.slides.length}</p>
  <hr/>
  ${slideElements}
</body>
</html>`;
}

function escapeHTML(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/** Built-in Skill Definition for Presentation Deck Generator */
export const presentationDeckSkill: SkillDefinition = {
  id: 'presentation.generate',
  name: 'Generate Presentation Deck',
  description:
    'Generate an interactive presentation slide deck (HTML/Markdown/AST) for technical architecture, PRs, or project reports. (Absorbed from Presenton)',
  category: 'file',
  enabled: true,
  version: SKILLS_VERSION,
  scopes: ['workspace'],
  status: 'ready',
  parameters: {
    title: { type: 'string', description: 'Title of the presentation', required: true },
    outline: {
      type: 'string',
      description: 'Markdown outline of sections and content',
      required: true,
    },
    theme: {
      type: 'string',
      description: 'Slide visual theme (ghita-neon, dark, light, cyberpunk)',
      required: false,
      default: 'ghita-neon',
    },
  },
  run: async ({ input }) => {
    const title = readString(input, 'title');
    const outline = readString(input, 'outline');
    const theme = (readString(input, 'theme') ?? 'ghita-neon') as SlideDeck['theme'];

    if (!title || !outline) {
      return fail('Missing required parameters: title and outline are required.');
    }

    const deck = generateSlideDeck(title, outline, theme);
    const html = renderSlideDeckToHTML(deck);

    return ok(`Successfully generated slide deck "${title}" with ${deck.slides.length} slides.`, {
      deck,
      html,
      slideCount: deck.slides.length,
    });
  },
};
