import type { SkillManifest } from './types.js';

export function getDefaultCatalog(): SkillManifest[] {
  const now = Date.now();
  return [
    {
      id: 'ghita.github-assistant',
      name: 'GitHub Assistant',
      description: 'Automate GitHub workflows: issues, PRs, releases, and code review.',
      version: '1.2.0',
      author: 'GHITA Dev Team',
      category: 'terminal',
      tags: ['git', 'github', 'automation', 'ci'],
      permissions: ['git', 'network'],
      downloads: 1250,
      rating: 4.5,
      ratingCount: 48,
      publishedAt: now - 86400000 * 30,
      updatedAt: now - 86400000 * 2,
    },
    {
      id: 'ghita.docker-orchestrator',
      name: 'Docker Container Orchestrator',
      description: 'Manage Docker containers, images, volumes, and networks.',
      version: '2.0.1',
      author: 'Docker Community',
      category: 'terminal',
      tags: ['docker', 'containers', 'devops'],
      permissions: ['docker', 'terminal'],
      downloads: 980,
      rating: 4.3,
      ratingCount: 35,
      publishedAt: now - 86400000 * 60,
      updatedAt: now - 86400000 * 5,
    },
    {
      id: 'ghita.vercel-deployer',
      name: 'Vercel Deployment Automation',
      description: 'Deploy to Vercel with one command. Preview URLs, rollback, and logs.',
      version: '1.0.3',
      author: 'Vercel Expert',
      category: 'terminal',
      tags: ['vercel', 'deploy', 'serverless'],
      permissions: ['network', 'fs'],
      downloads: 720,
      rating: 4.7,
      ratingCount: 22,
      publishedAt: now - 86400000 * 45,
      updatedAt: now - 86400000 * 7,
    },
    {
      id: 'ghita.db-client',
      name: 'Database Explorer Skill Pack',
      description: 'Query SQLite, PostgreSQL, and MySQL databases with safety guards.',
      version: '1.1.0',
      author: 'Database Pros',
      category: 'terminal',
      tags: ['database', 'sql', 'sqlite', 'postgres'],
      permissions: ['fs', 'network'],
      downloads: 540,
      rating: 4.1,
      ratingCount: 18,
      publishedAt: now - 86400000 * 90,
      updatedAt: now - 86400000 * 14,
    },
    {
      id: 'ghita.jira-connector',
      name: 'Jira Workspace Sync',
      description: 'Create, update, and transition Jira issues from the chat.',
      version: '1.3.0',
      author: 'Atlassian Community',
      category: 'terminal',
      tags: ['jira', 'project-management', 'agile'],
      permissions: ['network'],
      downloads: 430,
      rating: 4.0,
      ratingCount: 15,
      publishedAt: now - 86400000 * 120,
      updatedAt: now - 86400000 * 10,
    },
    {
      id: 'ghita.vision-grounding-extra',
      name: 'Advanced Visual Grounding SDK',
      description: 'Enhanced screenshot analysis with UI element detection and OCR.',
      version: '0.9.2',
      author: 'Vision AI Lab',
      category: 'computer',
      tags: ['vision', 'screenshot', 'ocr', 'computer-use'],
      permissions: ['screenshot', 'computer'],
      downloads: 310,
      rating: 4.4,
      ratingCount: 12,
      publishedAt: now - 86400000 * 20,
      updatedAt: now - 86400000 * 3,
    },
    {
      id: 'ghita.git-flow',
      name: 'Git Flow Automation',
      description: 'Automated git-flow workflows: feature, release, hotfix branches.',
      version: '1.0.0',
      author: 'GHITA Dev Team',
      category: 'terminal',
      tags: ['git', 'workflow', 'branching'],
      permissions: ['git'],
      downloads: 890,
      rating: 4.6,
      ratingCount: 30,
      publishedAt: now - 86400000 * 15,
      updatedAt: now - 86400000 * 1,
    },
    {
      id: 'ghita.test-runner-pro',
      name: 'Test Runner Pro',
      description: 'Advanced test runner with coverage, parallel execution, and reporting.',
      version: '1.2.0',
      author: 'Testing Guild',
      category: 'terminal',
      tags: ['testing', 'coverage', 'vitest', 'jest'],
      permissions: ['terminal', 'fs'],
      downloads: 670,
      rating: 4.2,
      ratingCount: 25,
      publishedAt: now - 86400000 * 40,
      updatedAt: now - 86400000 * 6,
    },
    {
      id: 'ghita.code-formatter-pack',
      name: 'Code Formatter Pack',
      description: 'Multi-language code formatting: Prettier, Black, rustfmt, clang-format.',
      version: '1.1.0',
      author: 'Code Quality Team',
      category: 'terminal',
      tags: ['formatting', 'prettier', 'black', 'rustfmt'],
      permissions: ['terminal', 'fs'],
      downloads: 520,
      rating: 4.3,
      ratingCount: 19,
      publishedAt: now - 86400000 * 50,
      updatedAt: now - 86400000 * 8,
    },
    {
      id: 'ghita.security-scanner',
      name: 'Security Scanner',
      description: 'Scan for vulnerabilities: npm audit, secret detection, OWASP patterns.',
      version: '1.0.0',
      author: 'Security Team',
      category: 'terminal',
      tags: ['security', 'audit', 'vulnerability'],
      permissions: ['terminal', 'network'],
      downloads: 410,
      rating: 4.5,
      ratingCount: 16,
      publishedAt: now - 86400000 * 25,
      updatedAt: now - 86400000 * 4,
    },
    {
      id: 'ghita.api-tester',
      name: 'API Tester',
      description: 'Test REST and GraphQL APIs with assertions and response validation.',
      version: '1.0.0',
      author: 'API Team',
      category: 'terminal',
      tags: ['api', 'rest', 'graphql', 'testing'],
      permissions: ['network'],
      downloads: 380,
      rating: 4.1,
      ratingCount: 14,
      publishedAt: now - 86400000 * 35,
      updatedAt: now - 86400000 * 9,
    },
    {
      id: 'ghita.env-manager',
      name: 'Environment Manager',
      description: 'Manage .env files, validate required variables, sync across environments.',
      version: '1.0.0',
      author: 'DevOps Team',
      category: 'file',
      tags: ['env', 'config', 'secrets'],
      permissions: ['fs'],
      downloads: 290,
      rating: 4.0,
      ratingCount: 11,
      publishedAt: now - 86400000 * 55,
      updatedAt: now - 86400000 * 12,
    },
    {
      id: 'ghita.readme-generator',
      name: 'README Generator',
      description: 'Auto-generate README.md from package.json, code structure, and JSDoc.',
      version: '1.0.0',
      author: 'Docs Team',
      category: 'file',
      tags: ['docs', 'readme', 'markdown'],
      permissions: ['fs'],
      downloads: 260,
      rating: 3.9,
      ratingCount: 10,
      publishedAt: now - 86400000 * 70,
      updatedAt: now - 86400000 * 15,
    },
    {
      id: 'ghita.changelog-gen',
      name: 'Changelog Generator',
      description: 'Generate CHANGELOG.md from git commits following Conventional Commits.',
      version: '1.0.0',
      author: 'Release Team',
      category: 'terminal',
      tags: ['changelog', 'git', 'release'],
      permissions: ['git', 'fs'],
      downloads: 230,
      rating: 4.2,
      ratingCount: 8,
      publishedAt: now - 86400000 * 80,
      updatedAt: now - 86400000 * 11,
    },
    {
      id: 'ghita.monorepo-tools',
      name: 'Monorepo Tools',
      description: 'Workspace management: dependency graph, affected packages, batch commands.',
      version: '1.0.0',
      author: 'Architecture Team',
      category: 'terminal',
      tags: ['monorepo', 'workspace', 'turbo', 'pnpm'],
      permissions: ['terminal', 'fs'],
      downloads: 340,
      rating: 4.4,
      ratingCount: 13,
      publishedAt: now - 86400000 * 42,
      updatedAt: now - 86400000 * 7,
    },
    {
      id: 'ghita.lighthouse-audit',
      name: 'Lighthouse Audit',
      description: 'Run Lighthouse performance audits on web apps with actionable reports.',
      version: '1.0.0',
      author: 'Performance Team',
      category: 'browser',
      tags: ['performance', 'lighthouse', 'audit'],
      permissions: ['browser', 'network'],
      downloads: 180,
      rating: 4.3,
      ratingCount: 7,
      publishedAt: now - 86400000 * 65,
      updatedAt: now - 86400000 * 13,
    },
    {
      id: 'ghita.screenshot-diff',
      name: 'Screenshot Diff',
      description: 'Compare screenshots before/after changes for visual regression testing.',
      version: '1.0.0',
      author: 'Visual Testing Team',
      category: 'screenshot',
      tags: ['screenshot', 'visual', 'regression', 'testing'],
      permissions: ['screenshot', 'fs'],
      downloads: 150,
      rating: 4.1,
      ratingCount: 6,
      publishedAt: now - 86400000 * 95,
      updatedAt: now - 86400000 * 16,
    },
    {
      id: 'ghita.file-organizer',
      name: 'File Organizer',
      description: 'Auto-organize files by type, date, or custom rules.',
      version: '1.0.0',
      author: 'Productivity Team',
      category: 'file',
      tags: ['files', 'organize', 'cleanup'],
      permissions: ['fs'],
      downloads: 200,
      rating: 3.8,
      ratingCount: 9,
      publishedAt: now - 86400000 * 100,
      updatedAt: now - 86400000 * 18,
    },
    {
      id: 'ghita.cron-scheduler',
      name: 'Cron Scheduler',
      description: 'Schedule and manage cron jobs with visual calendar and notifications.',
      version: '1.0.0',
      author: 'Automation Team',
      category: 'terminal',
      tags: ['cron', 'scheduler', 'automation'],
      permissions: ['terminal'],
      downloads: 270,
      rating: 4.0,
      ratingCount: 10,
      publishedAt: now - 86400000 * 58,
      updatedAt: now - 86400000 * 20,
    },
    {
      id: 'ghita.webhook-handler',
      name: 'Webhook Handler',
      description: 'Receive and process webhooks from GitHub, GitLab, Stripe, and custom sources.',
      version: '1.0.0',
      author: 'Integration Team',
      category: 'terminal',
      tags: ['webhook', 'integration', 'automation'],
      permissions: ['network'],
      downloads: 190,
      rating: 4.2,
      ratingCount: 8,
      publishedAt: now - 86400000 * 75,
      updatedAt: now - 86400000 * 22,
    },
  ];
}
