// v0.4.9 A2: Agent Governance — Default Policy Rules
//
// Baseline deny-default rule set for the GHITA agent runtime. These pair with
// the terminal blacklist in .ghita/security-blacklist.yaml to block the most
// destructive tool-calls before they reach an adapter.

import type { PolicyRule } from './types.js';

export const DEFAULT_POLICY_RULES: PolicyRule[] = [
  {
    id: 'deny-destructive-run-command',
    effect: 'deny',
    tool: 'run_command',
    action: 'execute',
    resourcePattern:
      /(?:rm\s+-rf\s+(?:\/|~|\$HOME)|mkfs(?:\.|\s)|dd\s+if=|:\(\)\s*\{|format(?:\.com)?\s+[a-z]:|del\s+\/[sfq]|remove-item\b(?=[^\r\n]*-recurse)(?=[^\r\n]*(?:[a-z]:\\(?:\s|$)|\/(?:\s|$)))|shutdown\b|reboot\b)/i,
    priority: 100,
    reason: 'Destructive command blocked by governance policy.',
  },
  {
    id: 'deny-system-write-tools',
    effect: 'deny',
    tool: 'write_file',
    action: 'write',
    resourcePattern: /^(?:\/etc\/|\/usr\/|\/bin\/|[A-Za-z]:\\Windows\\|\/System\/)/i,
    priority: 100,
    reason: 'Writing to an operating-system path is not permitted.',
  },
  {
    id: 'deny-system-replace-tools',
    effect: 'deny',
    tool: 'replace_file_content',
    action: 'write',
    resourcePattern: /^(?:\/etc\/|\/usr\/|\/bin\/|[A-Za-z]:\\Windows\\|\/System\/)/i,
    priority: 100,
    reason: 'Editing an operating-system path is not permitted.',
  },
  {
    id: 'allow-workspace-read-tools',
    effect: 'allow',
    tool: 'read_file',
    action: 'read',
    priority: 10,
    reason: 'Workspace file reads are allowed and remain sandboxed by the tool adapter.',
  },
  {
    id: 'allow-workspace-list-tools',
    effect: 'allow',
    tool: 'list_dir',
    action: 'read',
    priority: 10,
    reason: 'Workspace directory listing is allowed.',
  },
  {
    id: 'allow-workspace-search-tools',
    effect: 'allow',
    tool: 'grep_search',
    action: 'read',
    priority: 10,
    reason: 'Workspace text search is allowed.',
  },
  {
    id: 'allow-workspace-write-tools',
    effect: 'allow',
    tool: 'write_file',
    action: 'write',
    priority: 10,
    reason: 'Workspace writes are allowed after sandbox validation and approval.',
  },
  {
    id: 'allow-workspace-replace-tools',
    effect: 'allow',
    tool: 'replace_file_content',
    action: 'write',
    priority: 10,
    reason: 'Workspace edits are allowed after sandbox validation and approval.',
  },
  {
    id: 'allow-run-command-with-adapter-approval',
    effect: 'allow',
    tool: 'run_command',
    action: 'execute',
    priority: 10,
    reason: 'Commands are allowed only after terminal adapter approval and safety checks.',
  },
  {
    id: 'allow-web-search',
    effect: 'allow',
    tool: 'web_search',
    action: 'read',
    priority: 10,
    reason: 'Web search is allowed.',
  },
  {
    id: 'allow-web-fetch',
    effect: 'allow',
    tool: 'web_fetch',
    action: 'read',
    priority: 10,
    reason: 'Web fetch is allowed.',
  },
  {
    id: 'allow-code-intelligence',
    effect: 'allow',
    tool: 'index_codebase',
    action: 'read',
    priority: 10,
    reason: 'Local AST indexing is read-only and restricted to the active workspace.',
  },
  {
    id: 'allow-code-symbol-search',
    effect: 'allow',
    tool: 'search_code_symbols',
    action: 'read',
    priority: 10,
    reason: 'Searching the local workspace code graph is read-only.',
  },
  {
    id: 'allow-code-symbol-context',
    effect: 'allow',
    tool: 'get_symbol_context',
    action: 'read',
    priority: 10,
    reason: 'Reading local symbol relationships is allowed.',
  },
  {
    id: 'allow-code-repo-map',
    effect: 'allow',
    tool: 'get_repo_map',
    action: 'read',
    priority: 10,
    reason: 'Building a bounded local repository map is read-only.',
  },
  {
    id: 'allow-enabled-browser-observation',
    effect: 'allow',
    tool: 'browser_extract',
    action: 'read',
    priority: 10,
    reason: 'Page text extraction is allowed for an explicitly enabled browser skill.',
  },
  {
    id: 'allow-enabled-browser-actions',
    effect: 'allow',
    tool: 'browser_*',
    action: 'execute',
    priority: 10,
    reason: 'Enabled browser actions remain subject to runtime approval for mutations.',
  },
  {
    id: 'allow-workspace-memory-search',
    effect: 'allow',
    tool: 'memory_search',
    action: 'read',
    priority: 10,
    reason: 'Reading workspace-scoped memory is allowed.',
  },
  {
    id: 'allow-workspace-memory-write',
    effect: 'allow',
    tool: 'memory_remember',
    action: 'write',
    priority: 10,
    reason: 'Workspace memory writes require runtime approval and credential screening.',
  },
  {
    id: 'allow-workspace-memory-delete',
    effect: 'allow',
    tool: 'memory_forget',
    action: 'delete',
    priority: 10,
    reason: 'Workspace memory deletion requires runtime approval.',
  },
  // ── Hard denials (priority 100) ─────────────────────────────────────────
  {
    id: 'deny-destructive-shell',
    effect: 'deny',
    tool: 'terminal.*',
    action: 'execute',
    resourcePattern: /\b(?:rm\s+-rf\s+\/|mkfs|dd\s+if=|:\(\)\s*\{|format\s+[a-z]:|del\s+\/[sfq])/i,
    priority: 100,
    reason: 'Destructive shell command blocked by governance policy.',
  },
  {
    id: 'deny-fs-write-outside-workspace',
    effect: 'deny',
    tool: 'fs.*',
    action: 'write',
    resourcePattern: /^(?:\/etc\/|\/usr\/|\/bin\/|[A-Za-z]:\\Windows\\|\/System\/)/,
    priority: 100,
    reason: 'Writing to a system path is not permitted.',
  },
  {
    id: 'deny-fs-delete-outside-workspace',
    effect: 'deny',
    tool: 'fs.*',
    action: 'delete',
    resourcePattern: /^(?:\/etc\/|\/usr\/|\/bin\/|[A-Za-z]:\\Windows\\|\/System\/)/,
    priority: 100,
    reason: 'Deleting a system path is not permitted.',
  },

  // ── Explicit allowances (priority 10) ───────────────────────────────────
  {
    id: 'allow-fs-read',
    effect: 'allow',
    tool: 'fs.*',
    action: 'read',
    priority: 10,
    reason: 'Reading files is allowed within the workspace scope.',
  },
  {
    id: 'allow-fs-write-workspace',
    effect: 'allow',
    tool: 'fs.*',
    action: 'write',
    resourcePattern: /(?:ghita-workspace|[/\\]workspace[/\\])/,
    priority: 10,
    reason: 'Writing inside the workspace is allowed.',
  },
  {
    id: 'allow-browser-readonly',
    effect: 'allow',
    tool: 'browser.*',
    action: 'read',
    priority: 10,
    reason: 'Read-only browser observation is allowed.',
  },
  {
    id: 'allow-terminal-safe',
    effect: 'allow',
    tool: 'terminal.*',
    action: 'execute',
    resourcePattern: /^(?:git|pnpm|npm|node|tsc|vitest|eslint|ls|cat|pwd|echo)\b/,
    priority: 10,
    reason: 'Whitelisted development command.',
  },
];
