// Renders presentation slide decks generated by the presentation.generate skill.
// Absorbed & enhanced from Presenton reference project.

import React, { useState } from 'react';

export interface SlideComponentData {
  type: 'heading' | 'text' | 'code' | 'list' | 'image' | 'quote';
  content: string;
  language?: string;
  items?: string[];
}

export interface SlideData {
  id: string;
  title: string;
  subtitle?: string;
  layout: string;
  components: SlideComponentData[];
}

export interface SlideDeckData {
  title: string;
  author?: string;
  theme: string;
  slides: SlideData[];
}

export interface SlideViewerProps {
  deck: SlideDeckData;
  onClose?: () => void;
}

export const SlideViewer: React.FC<SlideViewerProps> = ({ deck, onClose }) => {
  const [currentSlideIndex, setCurrentSlideIndex] = useState(0);

  const currentSlide = deck.slides[currentSlideIndex] ?? deck.slides[0];

  const handleNext = () => {
    if (currentSlideIndex < deck.slides.length - 1) {
      setCurrentSlideIndex((prev) => prev + 1);
    }
  };

  const handlePrev = () => {
    if (currentSlideIndex > 0) {
      setCurrentSlideIndex((prev) => prev - 1);
    }
  };

  if (!currentSlide) {
    return <div className="p-4 text-red-400">No slides available in deck.</div>;
  }

  return (
    <div className="flex flex-col h-full bg-slate-950 text-slate-100 rounded-lg overflow-hidden border border-slate-800 shadow-2xl">
      {/* Header Bar */}
      <div className="flex items-center justify-between px-4 py-3 bg-slate-900 border-b border-slate-800">
        <div className="flex items-center space-x-2">
          <span className="px-2 py-0.5 text-xs font-semibold bg-sky-500/20 text-sky-400 border border-sky-500/30 rounded">
            GHITA Slide Engine
          </span>
          <h3 className="font-semibold text-sm truncate max-w-xs">{deck.title}</h3>
        </div>
        <div className="flex items-center space-x-2 text-xs text-slate-400">
          <span>
            Slide {currentSlideIndex + 1} / {deck.slides.length}
          </span>
          {onClose && (
            <button
              onClick={onClose}
              className="p-1 hover:bg-slate-800 rounded text-slate-400 hover:text-slate-200 transition"
              title="Close Presentation"
            >
              ✕
            </button>
          )}
        </div>
      </div>

      {/* Slide Body Viewport */}
      <div className="flex-1 p-8 flex flex-col justify-between bg-slate-900/60 overflow-y-auto">
        <div>
          <div className="text-xs font-mono uppercase tracking-widest text-sky-400 mb-2">
            Layout: {currentSlide.layout}
          </div>
          <h2 className="text-2xl font-bold text-white mb-1">{currentSlide.title}</h2>
          {currentSlide.subtitle && (
            <h4 className="text-sm text-slate-400 mb-6">{currentSlide.subtitle}</h4>
          )}

          <div className="space-y-4 mt-6">
            {currentSlide.components.map((comp, idx) => {
              if (comp.type === 'code') {
                return (
                  <pre
                    key={idx}
                    className="p-4 rounded-lg bg-slate-950 border border-slate-800 text-emerald-400 font-mono text-xs overflow-x-auto"
                  >
                    <code>{comp.content}</code>
                  </pre>
                );
              }
              if (comp.type === 'list' && comp.items) {
                return (
                  <ul key={idx} className="list-disc list-inside space-y-2 text-slate-200 text-sm">
                    {comp.items.map((item, i) => (
                      <li key={i}>{item}</li>
                    ))}
                  </ul>
                );
              }
              return (
                <p key={idx} className="text-slate-300 text-sm leading-relaxed">
                  {comp.content}
                </p>
              );
            })}
          </div>
        </div>

        {/* Footer Navigation Bar */}
        <div className="flex items-center justify-between pt-6 border-t border-slate-800 mt-6 text-xs text-slate-400">
          <div>Theme: {deck.theme}</div>
          <div className="flex space-x-2">
            <button
              onClick={handlePrev}
              disabled={currentSlideIndex === 0}
              className="px-3 py-1.5 rounded bg-slate-800 hover:bg-slate-700 disabled:opacity-40 transition"
            >
              ← Previous
            </button>
            <button
              onClick={handleNext}
              disabled={currentSlideIndex === deck.slides.length - 1}
              className="px-3 py-1.5 rounded bg-sky-600 hover:bg-sky-500 text-white font-medium disabled:opacity-40 transition"
            >
              Next →
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
