export interface APTask {
    taskId: string;
    input: string;
    additionalInput?: Record<string, any>;
    artifacts: APArtifact[];
    steps: APStep[];
    createdAt: string;
}
export interface APStep {
    stepId: string;
    taskId: string;
    name: string;
    input: string;
    status: 'created' | 'running' | 'completed' | 'failed';
    output?: string;
    artifacts: APArtifact[];
    isLast: boolean;
    createdAt: string;
}
export interface APArtifact {
    artifactId: string;
    fileName: string;
    relativePath: string;
    agentCreated: boolean;
}
/**
 * Standard Agent Protocol Compliance Server implementation.
 * Maps standard REST endpoints defined by http://agentprotocol.ai
 */
export declare class AgentProtocolServer {
    private tasks;
    /**
     * POST /ap/v1/agent/tasks
     * Create a new task for the AI Agent
     */
    createTask(input: string, additionalInput?: Record<string, any>): APTask;
    /**
     * GET /ap/v1/agent/tasks
     * List all task IDs managed by this agent
     */
    listTasks(): string[];
    /**
     * GET /ap/v1/agent/tasks/:taskId
     * Retrieve a specific task by ID
     */
    getTask(taskId: string): APTask | undefined;
    /**
     * POST /ap/v1/agent/tasks/:taskId/steps
     * Execute the next step in a task
     */
    executeStep(taskId: string, input: string): APStep | undefined;
    /**
     * GET /ap/v1/agent/tasks/:taskId/steps
     * Retrieve all steps executed for a task
     */
    getTaskSteps(taskId: string): APStep[];
    /**
     * GET /ap/v1/agent/tasks/:taskId/steps/:stepId
     * Get specific details about a step
     */
    getStep(taskId: string, stepId: string): APStep | undefined;
    /**
     * GET /ap/v1/agent/tasks/:taskId/artifacts
     * List files/artifacts generated by the task execution
     */
    getTaskArtifacts(taskId: string): APArtifact[];
    /**
     * Add a mock artifact to a task for testing purposes
     */
    addArtifact(taskId: string, fileName: string, relativePath: string): APArtifact | undefined;
}
//# sourceMappingURL=ap.d.ts.map