// ==============================================================================
// GHITA CODING AGENT — Agent Protocol (AP) Standard Server Implementation
// ==============================================================================
import { generateUUID } from '@ghita/shared';
/**
 * Standard Agent Protocol Compliance Server implementation.
 * Maps standard REST endpoints defined by http://agentprotocol.ai
 */
export class AgentProtocolServer {
    tasks = new Map();
    /**
     * POST /ap/v1/agent/tasks
     * Create a new task for the AI Agent
     */
    createTask(input, additionalInput) {
        const taskId = `task-${generateUUID()}`;
        const newTask = {
            taskId,
            input,
            additionalInput,
            artifacts: [],
            steps: [],
            createdAt: new Date().toISOString(),
        };
        this.tasks.set(taskId, newTask);
        return newTask;
    }
    /**
     * GET /ap/v1/agent/tasks
     * List all task IDs managed by this agent
     */
    listTasks() {
        return Array.from(this.tasks.keys());
    }
    /**
     * GET /ap/v1/agent/tasks/:taskId
     * Retrieve a specific task by ID
     */
    getTask(taskId) {
        return this.tasks.get(taskId);
    }
    /**
     * POST /ap/v1/agent/tasks/:taskId/steps
     * Execute the next step in a task
     */
    executeStep(taskId, input) {
        const task = this.tasks.get(taskId);
        if (!task)
            return undefined;
        const stepId = `step-${generateUUID()}`;
        const newStep = {
            stepId,
            taskId,
            name: `Step #${task.steps.length + 1}`,
            input,
            status: 'completed',
            output: `Executed step successfully: ${input}`,
            artifacts: [],
            isLast: false,
            createdAt: new Date().toISOString(),
        };
        task.steps.push(newStep);
        return newStep;
    }
    /**
     * GET /ap/v1/agent/tasks/:taskId/steps
     * Retrieve all steps executed for a task
     */
    getTaskSteps(taskId) {
        const task = this.tasks.get(taskId);
        return task ? task.steps : [];
    }
    /**
     * GET /ap/v1/agent/tasks/:taskId/steps/:stepId
     * Get specific details about a step
     */
    getStep(taskId, stepId) {
        const task = this.tasks.get(taskId);
        if (!task)
            return undefined;
        return task.steps.find((s) => s.stepId === stepId);
    }
    /**
     * GET /ap/v1/agent/tasks/:taskId/artifacts
     * List files/artifacts generated by the task execution
     */
    getTaskArtifacts(taskId) {
        const task = this.tasks.get(taskId);
        return task ? task.artifacts : [];
    }
    /**
     * Add a mock artifact to a task for testing purposes
     */
    addArtifact(taskId, fileName, relativePath) {
        const task = this.tasks.get(taskId);
        if (!task)
            return undefined;
        const artifact = {
            artifactId: `art-${generateUUID()}`,
            fileName,
            relativePath,
            agentCreated: true,
        };
        task.artifacts.push(artifact);
        return artifact;
    }
}
//# sourceMappingURL=ap.js.map