// ==============================================================================
// GHITA CODING AGENT — Agent Protocol (AP) Standard Server Implementation
// ==============================================================================

import { generateUUID } from '@ghita/shared';

export interface APTask {
  taskId: string;
  input: string;
  additionalInput?: Record<string, unknown>;
  artifacts: APArtifact[];
  steps: APStep[];
  createdAt: string;
}

export interface APStep {
  stepId: string;
  taskId: string;
  name: string;
  input: string;
  status: 'created' | 'running' | 'completed' | 'failed';
  output?: string;
  artifacts: APArtifact[];
  isLast: boolean;
  createdAt: string;
}

export interface APArtifact {
  artifactId: string;
  fileName: string;
  relativePath: string;
  agentCreated: boolean;
}

/**
 * Standard Agent Protocol Compliance Server implementation.
 * Maps standard REST endpoints defined by http://agentprotocol.ai
 */
export class AgentProtocolServer {
  private tasks: Map<string, APTask> = new Map();

  /**
   * POST /ap/v1/agent/tasks
   * Create a new task for the AI Agent
   */
  public createTask(input: string, additionalInput?: Record<string, unknown>): APTask {
    const taskId = `task-${generateUUID()}`;
    const newTask: APTask = {
      taskId,
      input,
      additionalInput,
      artifacts: [],
      steps: [],
      createdAt: new Date().toISOString(),
    };
    this.tasks.set(taskId, newTask);
    return newTask;
  }

  /**
   * GET /ap/v1/agent/tasks
   * List all task IDs managed by this agent
   */
  public listTasks(): string[] {
    return Array.from(this.tasks.keys());
  }

  /**
   * GET /ap/v1/agent/tasks/:taskId
   * Retrieve a specific task by ID
   */
  public getTask(taskId: string): APTask | undefined {
    return this.tasks.get(taskId);
  }

  /**
   * POST /ap/v1/agent/tasks/:taskId/steps
   * Execute the next step in a task
   */
  public executeStep(taskId: string, input: string): APStep | undefined {
    const task = this.tasks.get(taskId);
    if (!task) return undefined;

    const stepId = `step-${generateUUID()}`;
    const newStep: APStep = {
      stepId,
      taskId,
      name: `Step #${task.steps.length + 1}`,
      input,
      status: 'completed',
      output: `Executed step successfully: ${input}`,
      artifacts: [],
      isLast: false,
      createdAt: new Date().toISOString(),
    };

    task.steps.push(newStep);
    return newStep;
  }

  /**
   * GET /ap/v1/agent/tasks/:taskId/steps
   * Retrieve all steps executed for a task
   */
  public getTaskSteps(taskId: string): APStep[] {
    const task = this.tasks.get(taskId);
    return task ? task.steps : [];
  }

  /**
   * GET /ap/v1/agent/tasks/:taskId/steps/:stepId
   * Get specific details about a step
   */
  public getStep(taskId: string, stepId: string): APStep | undefined {
    const task = this.tasks.get(taskId);
    if (!task) return undefined;
    return task.steps.find((s) => s.stepId === stepId);
  }

  /**
   * GET /ap/v1/agent/tasks/:taskId/artifacts
   * List files/artifacts generated by the task execution
   */
  public getTaskArtifacts(taskId: string): APArtifact[] {
    const task = this.tasks.get(taskId);
    return task ? task.artifacts : [];
  }

  /**
   * Add a mock artifact to a task for testing purposes
   */
  public addArtifact(taskId: string, fileName: string, relativePath: string): APArtifact | undefined {
    const task = this.tasks.get(taskId);
    if (!task) return undefined;

    const artifact: APArtifact = {
      artifactId: `art-${generateUUID()}`,
      fileName,
      relativePath,
      agentCreated: true,
    };
    task.artifacts.push(artifact);
    return artifact;
  }
}
