export declare const DOCKERFILE_TEMPLATE = "\nFROM node:20-alpine AS builder\nWORKDIR /app\nCOPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./\nCOPY packages/shared/package.json ./packages/shared/\nCOPY packages/ai-engine/package.json ./packages/ai-engine/\nRUN npm install -g pnpm && pnpm install --frozen-lockfile\nCOPY . .\nRUN pnpm --filter @ghita/shared build && pnpm --filter @ghita/ai-engine build\n\nFROM node:20-alpine AS runner\nWORKDIR /app\nCOPY --from=builder /app/package.json /app/pnpm-lock.yaml /app/pnpm-workspace.yaml ./\nCOPY --from=builder /app/node_modules ./node_modules\nCOPY --from=builder /app/packages/shared/dist ./packages/shared/dist\nCOPY --from=builder /app/packages/shared/package.json ./packages/shared/package.json\nCOPY --from=builder /app/packages/ai-engine/dist ./packages/ai-engine/dist\nCOPY --from=builder /app/packages/ai-engine/package.json ./packages/ai-engine/package.json\nEXPOSE 3001\nENV PORT=3001\nCMD [\"node\", \"packages/ai-engine/dist/platform/gateway.js\"]\n";
export declare const DOCKER_COMPOSE_TEMPLATE = "\nversion: '3.8'\nservices:\n  ai-gateway:\n    build:\n      context: .\n      dockerfile: Dockerfile.gateway\n    ports:\n      - \"3001:3001\"\n    environment:\n      - PORT=3001\n      - OPENAI_API_KEY=${OPENAI_API_KEY}\n    restart: always\n";
export declare const K8S_DEPLOYMENT_TEMPLATE = "\napiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: ghita-ai-gateway\n  labels:\n    app: ghita-ai-gateway\nspec:\n  replicas: 2\n  selector:\n    matchLabels:\n      app: ghita-ai-gateway\n  template:\n    metadata:\n      labels:\n        app: ghita-ai-gateway\n    spec:\n      containers:\n      - name: gateway\n        image: ghita-truongle/ai-gateway:latest\n        ports:\n        - containerPort: 3001\n        env:\n        - name: PORT\n          value: \"3001\"\n        - name: OPENAI_API_KEY\n          valueFrom:\n            secretKeyRef:\n              name: openai-secrets\n              key: api-key\n---\napiVersion: v1\nkind: Service\nmetadata:\n  name: ghita-ai-gateway-service\nspec:\n  selector:\n    app: ghita-ai-gateway\n  ports:\n    - protocol: TCP\n      port: 80\n      targetPort: 3001\n  type: LoadBalancer\n";
export declare const TERRAFORM_TEMPLATE = "\nvariable \"gcp_project_id\" {\n  type        = string\n  description = \"The GCP project ID to deploy to\"\n}\n\nvariable \"region\" {\n  type    = string\n  default = \"us-central1\"\n}\n\nresource \"google_cloud_run_v2_service\" \"ai_gateway\" {\n  name     = \"ghita-ai-gateway\"\n  location = var.region\n  ingress  = \"INGRESS_TRAFFIC_ALL\"\n\n  template {\n    containers {\n      image = \"gcr.io/${var.gcp_project_id}/ai-gateway:latest\"\n      ports {\n        container_port = 3001\n      }\n      env {\n        name  = \"PORT\"\n        value = \"3001\"\n      }\n      env {\n        name  = \"OPENAI_API_KEY\"\n        value = \"your-api-key-here\"\n      }\n    }\n  }\n}\n";
export declare class DeployConfigGenerator {
    generateDockerfile(): string;
    generateDockerCompose(): string;
    generateK8s(): string;
    generateTerraform(): string;
}
//# sourceMappingURL=prometheus.d.ts.map