import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  mainSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: ['getting-started', 'installation', 'configuration', 'faq'],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: ['architecture', 'architecture-overview', 'packages', 'data-flow'],
    },
    {
      type: 'category',
      label: 'Features',
      items: [
        'features/multi-provider',
        'features/skills',
        'features/computer-use',
        'features/memory',
        'features/marketplace',
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: ['tutorials/first-agent', 'tutorials/custom-skill', 'tutorials/multi-modal'],
    },
    {
      type: 'category',
      label: 'Security',
      items: ['security', 'security-guide'],
    },
    {
      type: 'category',
      label: 'Operations',
      items: ['deployment', 'monitoring', 'contributing', 'troubleshooting'],
    },
  ],
  apiSidebar: [
    {
      type: 'autogenerated',
      dirName: 'api', // TypeDoc will output here
    },
  ],
};

export default sidebars;
